## BOW, TF-IDF, Machine Learning Algotithms

1. Preprocessing And Cleaning

2. Train Test Split

3. BOW AND TF-IDF (Sentence ---> Vectors) {Preventing Data Leakage}

4. Trained Models

In [2]:
import pandas as pd

messages = pd.read_csv('https://raw.githubusercontent.com/krishnaik06/Complete-Data-Science-With-Machine-Learning-And-NLP-2024/refs/heads/main/26-CompleteNLP%20For%20Machine%20Learning/Practicals/SpamClassifier-master/smsspamcollection/SMSSpamCollection',sep='\t',names=["label","message"])

In [3]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [4]:
## Data Cleaning

import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [5]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [6]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [7]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

# Create Bag of Words model

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features = 100, ngram_range=(1,2))

In [9]:
# Independent feature

X=cv.fit_transform(corpus).toarray()

In [10]:
import numpy as np
np.set_printoptions(edgeitems = 30, linewidth = 100000,formatter= dict(float=lambda x: '%.3g' % x))

In [11]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0

In [12]:
cv.vocabulary_

{'go': np.int64(22),
 'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(91),
 'ok': np.int64(58),
 'free': np.int64(18),
 'win': np.int64(95),
 'text': np.int64(78),
 'txt': np.int64(87),
 'say': np.int64(69),
 'alreadi': np.int64(0),
 'think': np.int64(81),
 'hey': np.int64(28),
 'week': np.int64(93),
 'back': np.int64(4),
 'like': np.int64(39),
 'still': np.int64(74),
 'send': np.int64(71),
 'even': np.int64(15),
 'friend': np.int64(19),
 'prize': np.int64(64),
 'claim': np.int64(8),
 'call': np.int64(5),
 'mobil': np.int64(49),
 'co': np.int64(9),
 'home': np.int64(30),
 'want': np.int64(90),
 'today': np.int64(83),
 'cash': np.int64(7),
 'day': np.int64(12),
 'repli': np.int64(66),
 'www': np.int64(97),
 'right': np.int64(67),
 'thank': np.int64(79),
 'take': np.int64(76),
 'time': np.int64(82),
 'messag': np.int64(46),
 'oh': np.int64(57),
 'ye': np.int64(98),
 'make': np.int64(44),
 'way': np.int64(92),
 'feel': np.int64(16),
 'dont': np.int64(14),
 'miss': np.int64(4

In [13]:
#. Dependent Feature

y = pd.get_dummies(messages['label'])

In [14]:
y

,ham,spam
0,True,False
1,True,False
2,False,True
3,True,False
4,True,False
...,...,...
5567,False,True
5568,True,False
5569,True,False
5570,True,False


In [15]:
y=y.iloc[:,0].values

In [16]:
 # Train Test Split

from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [18]:
X_train.shape

(4457, 100)

In [19]:
y_train.shape

(4457,)

In [20]:
from sklearn.naive_bayes import MultinomialNB

In [21]:
mnb = MultinomialNB()

In [22]:
spam_detect_model = mnb.fit(X_train, y_train)

In [23]:
spam_detect_model

MultinomialNB()

In [24]:
y_pred= spam_detect_model.predict(X_test)

In [25]:
from sklearn.metrics import accuracy_score, classification_report

In [26]:
accuracy_score(y_pred, y_test)

0.9605381165919282

In [27]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.80      0.90      0.85       134
        True       0.99      0.97      0.98       981

    accuracy                           0.96      1115
   macro avg       0.89      0.94      0.91      1115
weighted avg       0.96      0.96      0.96      1115



# Creating the TF-IDF Model

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features = 2500, ngram_range=(1,2))

X=tv.fit_transform(corpus).toarray()

In [29]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [30]:
tv.vocabulary_

{'go': np.int64(819),
 'point': np.int64(1629),
 'crazi': np.int64(457),
 'avail': np.int64(123),
 'bugi': np.int64(234),
 'great': np.int64(867),
 'world': np.int64(2420),
 'la': np.int64(1104),
 'cine': np.int64(356),
 'got': np.int64(858),
 'wat': np.int64(2324),
 'ok': np.int64(1476),
 'lar': np.int64(1117),
 'joke': np.int64(1062),
 'wif': np.int64(2376),
 'oni': np.int64(1498),
 'ok lar': np.int64(1479),
 'free': np.int64(746),
 'entri': np.int64(623),
 'wkli': np.int64(2403),
 'comp': np.int64(407),
 'win': np.int64(2381),
 'cup': np.int64(472),
 'final': np.int64(703),
 'st': np.int64(1964),
 'may': np.int64(1272),
 'text': np.int64(2087),
 'receiv': np.int64(1714),
 'question': np.int64(1683),
 'std': np.int64(1980),
 'txt': np.int64(2200),
 'rate': np.int64(1695),
 'appli': np.int64(87),
 'free entri': np.int64(752),
 'entri wkli': np.int64(625),
 'wkli comp': np.int64(2404),
 'std txt': np.int64(1981),
 'txt rate': np.int64(2206),
 'rate appli': np.int64(1696),
 'dun': np.in

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_tast = train_test_split(X, y, test_size = 0.20)

In [40]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [41]:
spam_tfidf_model

MultinomialNB()

In [42]:
y_pred= spam_tfidf_model.predict(X_test)

In [43]:
y_pred

array([ True,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, ...,  True, False, False,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True])

In [44]:
from sklearn.metrics import accuracy_score, classification_report

In [45]:
print(accuracy_score(y_pred, y_test))

0.7829596412556054


In [47]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

       False       0.12      0.14      0.13       126
        True       0.89      0.86      0.88       989

    accuracy                           0.78      1115
   macro avg       0.50      0.50      0.50      1115
weighted avg       0.80      0.78      0.79      1115

